name: Workflow example
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # Clone le repository dans la VM runner
      - uses: actions/checkout@v3
      - name: "run linter"
        run: "npm run lint"
      - name: "run unit-tests"
        run: "npm run test-unit"
      - name: "run test e2E"
        run: "npm run test-e2e"
  

