name: Workflow example
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      # Clone le repository dans la VM runner
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: "Lint"
        run: "npm run lint"

      - name: "Test-unit"
        run: "npm run test-unit"

      - name: "Test-e2e"
        run: "npm run test-e2e"



