name: Workflow example
on:
  #push:
  #branches:
  #- main
  pull_request:
env: # environment variables (available in any part of the action)
  NODE_VERSION: 16
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # Clone le repository dans la VM runner
      - uses: actions/checkout@v3
      - name: "Hello world"
        run: "npm run lint"
        with:
          node-version: ${{ env.NODE_VERSION }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v3
      - name: "Hello world"
        run: "npm run test-unit"
        with:
          node-version: ${{ env.NODE_VERSION }}
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - uses: actions/checkout@v3
      - name: "Hello world"
        run: "npm run test-e2e"
        with:
          node-version: ${{ env.NODE_VERSION }}



